# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNative4Days' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNative4Days
  pod 'JTSImageViewController'

  target 'ReactNative4DaysTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
